### PR TITLE
fix some typo while I am translating it into Chinese

### PR DESCRIPTION
**Pull request by HelloRWA**

### CODE REVIEW

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — CHANGES_REQUESTED** [review]
Because this isn't done in either a .lua file or in .editor, this is technically a `bash` mark rather than a `lua` mark.

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Review by PSkinnerTech — APPROVED** [review]

**Comment by HelloRWA** [comment]
> Because this isn't done in either a .lua file or in .editor, this is technically a `bash` mark rather than a `lua` mark.

which line of code I should update? I do not find the link to the line of code on this page.

**Comment by twilson63** [comment]
@HelloRWA Do you know Outprog and the PermaDAO? they are also translating to chinese want to join forces?

**Comment by HelloRWA** [comment]
> @HelloRWA Do you know Outprog and the PermaDAO? they are also translating to chinese want to join forces?
I am one of them already ;) 
I have done 50% of the translation ;) 
Just done with some updates about the i18n config for vitepress, will make a PR soon!

AO~~!!

**Pull request merged**
