### PR TITLE
Added Turkish (tr) language for ao-cookbook

### PR DESCRIPTION
**Pull request by sukrucildirr**

### CODE REVIEW

**Comment by twilson63** [comment]
This is great, is your plan to translate all of the readme files to Turkish as well?

**Comment by twilson63** [comment]
Getting errors trying to review

failed to load config from /workspace/ao-cookbook/src/.vitepress/config.js
failed to start server. error:
ReferenceError: trStrings is not defined
    at file:///workspace/ao-cookbook/src/.vitepress/config.js.timestamp-1709591348353-5a1d5cbd65a22.mjs:16:14
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadConfigFromBundledFile (file:///workspace/ao-cookbook/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:68152:21)
    at async loadConfigFromFile (file:///workspace/ao-cookbook/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:68007:28)
    at async resolveUserConfig (file:///workspace/ao-cookbook/node_modules/vitepress/dist/node/serve-Bbz0dL6j.js:19985:27)
    at async resolveConfig (file:///workspace/ao-cookbook/node_modules/vitepress/dist/node/serve-Bbz0dL6j.js:19905:48)
    at async createServer (file:///workspace/ao-cookbook/node_modules/vitepress/dist/node/serve-Bbz0dL6j.js:63802:18)
    at async createDevServer (file:///workspace/ao-cookbook/node_modules/vitepress/dist/node/cli.js:405:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sukrucildirr** [comment]
It is interesting. I did everything on languages/README.md
-I created tr.json into strings folder.
-I added tr language to the language array in def.js
-I created tr folder into src folder.

I did wrong something? And yes, i can translate main README.md file too but I couldn't see instructions.

**Comment by twilson63** [comment]
Try running npm install and npm run dev and make sure it works on your machine

**Comment by twilson63** [comment]
All the document files are in the src folder, did you translate all of those pages I just did not see it n your PR

**Comment by twilson63** [comment]
I would expect a turkish file for each file in src

**Comment by sukrucildirr** [comment]
Okay i will translate each file under src but i didn't understand file system.

How it will looks like?

src/tr/src/(all files under src + even with translating file names) ?

**Comment by twilson63** [comment]
Here is a guide

https://vitepress.dev/guide/i18n#internationalization

**Comment by sukrucildirr** [comment]
Can you send me dm on twitter or can you send me email please ?

email : sukrucildirr@gmail.com
twitter : sukrucildirr

**Pull request closed without merging**
