### PR TITLE
Add crypto module docs

### PR DESCRIPTION
**Pull request by Envoy-VC**
This PR adds documentation for the crypto module.

- Add crypto module docs
- Update Modules Table of contents
- Add crypto module in sidebar

### CODE REVIEW

**Review by twilson63 — APPROVED** [review]
LGTM

**Comment by PSkinnerTech** [comment]
Hey @Envoy-VC!

Is this PR ready for final review, or are you expecting to make more changes?

**Comment by Envoy-VC** [comment]
> Hey @Envoy-VC!
> 
> 
> 
> Is this PR ready for final review, or are you expecting to make more changes?

Yes, it's ready for final review.

**Comment by PSkinnerTech** [comment]
Hey @Envoy-VC! Can you resolve the conflicts so that I can merge?

**Comment by PSkinnerTech** [comment]
Thanks for making the changes!

**Pull request merged**
