### PR TITLE
FEAT: 0rbit Tutorials 

### PR DESCRIPTION
**Pull request by megabyte0x**
The PR contains the tutorials on how to build with [0rbit](0rbit.co)

This PR is referenced from the issue #132

### CODE REVIEW

**Comment by PSkinnerTech** [comment]
After some discussion, we need to have this as a "Guide" rather than a "Tutorial", since this is a third-party guide that is being used.  Tutorials will only be for interactive tutorials that use only AO/AOS.  We'll also be creating a something along the lines of a "Preferred Partners" page that will list Orbit as a Preferred Partner and will link directly to the Orbit documentation.

**Comment by megabyte0x** [comment]
> After some discussion, we need to have this as a "Guide" rather than a "Tutorial", since this is a third-party guide that is being used. Tutorials will only be for interactive tutorials that use only AO/AOS. We'll also be creating a something along the lines of a "Preferred Partners" page that will list Orbit as a Preferred Partner and will link directly to the Orbit documentation.

Thanks for the review. I want to confirm where I shall make the changes. Shall I move the tutorials to guide or create a preferred partners category and add it there?

**Comment by PSkinnerTech** [comment]
Hey @megabyte0x!

Ya, move it over to a guide, then I'll review it again.

**Comment by megabyte0x** [comment]
> Hey @megabyte0x!
> 
> Ya, move it over to a guide, then I'll review it again.

Gotcha! Will do

**Comment by megabyte0x** [comment]
hey @PSkinnerTech 

I just checked the https://cookbook_ao.arweave.dev and saw that someone has removed(mistakenly) 0rbit as a category from the guides section in the navbar, though the content is still available on the first page of the [Guides](https://cookbook_ao.arweave.dev/guides/index.html).

I would request you to reopen this PR or let me know if I require to create a new one to fix this.

**Pull request merged**
