### PR TITLE
feat: add cred and quests zh translate and fix zh testnet-info path error

### PR DESCRIPTION
**Pull request by HelloRWA**

### CODE REVIEW

**Comment by PSkinnerTech** [comment]
Hey @HelloRWA!

Is this still a work in progress, or is ready to be reviewed?

If this is still a work in progress, can you add `[WIP]` to the beginning of the PR title?

When it's ready for review, can you tag me as a requested reviewer?

Thanks!

**Comment by HelloRWA** [comment]
> Hey @HelloRWA!
> 
> Is this still a work in progress, or is ready to be reviewed?
> 
> If this is still a work in progress, can you add `[WIP]` to the beginning of the PR title?
> 
> When it's ready for review, can you tag me as a requested reviewer?
> 
> Thanks!

Hi @PSkinnerTech 
  Ya! it's already done, wait for the review!
   Next time I will directly tag you as a requested reviewer! I believed I will make more PR on ao/aos/cookbook projects ;)

**Comment by PSkinnerTech** [comment]
Hey @HelloRWA, can you resolve the conflicts so that I can merge?

**Comment by PSkinnerTech** [comment]
Fixed the conflicts and merging.

**Pull request merged**
